testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "sk_test_" #only needed if using Stripe
stripe_api_key = "sk_live" #only needed if using Stripe
stripe_link = "https://buy.stripe.com/" #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/" #only needed if using Stripe
redirect_url_test = 'http://195.35.1.37:8501'
redirect_url = "http://195.35.1.37:8501"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/21talents" #only needed if using buy me a coffee
client_id = '364894456890-bu3ksjkmq6ehqotr675fmkhet8u00dlm.apps.googleusercontent.com'
client_secret = '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'
redirect_url = 'http://195.35.1.37:8501'